name: Build

# Build project on develop pushes
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd lib/functions/assets-cleanup && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../../..
          pnpm install --frozen-lockfile

      - name: Build project
        run: |
          cd lib/functions/assets-cleanup && pnpm run build && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && pnpm run build && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && pnpm run build && cd ../../../..
          pnpm run build