name: Build

# Build project on develop pushes
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          cd lib/functions/assets-cleanup && yarn install --frozen-lockfile && yarn install-layer && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && yarn install --frozen-lockfile && yarn install-layer && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && yarn install --frozen-lockfile && yarn install-layer && cd ../../../..
          yarn install --frozen-lockfile

      - name: Build project
        run: |
          cd lib/functions/assets-cleanup && yarn build && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && yarn build && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && yarn build && cd ../../../..
          yarn build