name: Create Release PR

on:
  workflow_dispatch: {}
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: create-release-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_pr:
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: |
          cd lib/functions/assets-cleanup && pnpm install --frozen-lockfile && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && pnpm install --frozen-lockfile && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && pnpm install --frozen-lockfile && cd ../../../..
          pnpm install --frozen-lockfile

      - name: Generate changelog and bump version
        id: changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          pnpm changelogen --release
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(release): v$VERSION"
          else
            echo "No changelog/package changes to commit."
          fi

      - name: Create Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): v${{ steps.changelog.outputs.version }}"
          title: "chore(release): v${{ steps.changelog.outputs.version }}"
          body: "Automated release PR for v${{ steps.changelog.outputs.version }}. Please review and merge."
          base: master
          branch: develop
          labels: release
