name: Publish

on:
  push:
    tags:
      - '**' # Listen to push of every tag format, including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

      # Init cache to speed up yarn install
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd lib/functions/assets-cleanup && yarn install --frozen-lockfile && yarn install-layer && cd ../../..
          yarn install --frozen-lockfile

      - name: Build project
        run: |
          cd lib/functions/assets-cleanup && yarn build && cd ../../..
          yarn build

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}