name: Publish

on:
  push:
    tags:
      - '**' # Listen to push of every tag format, including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

      - name: Install dependencies
        run: |
          cd lib/functions/assets-cleanup && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && pnpm install --frozen-lockfile && pnpm install-layer && cd ../../../..
          pnpm install --frozen-lockfile

      - name: Build project
        run: |
          cd lib/functions/assets-cleanup && pnpm build && cd ../../..
          cd lib/functions/access-logs-analysis/group-by-date && pnpm build && cd ../../../..
          cd lib/functions/access-logs-analysis/partitioning && pnpm build && cd ../../../..
          pnpm build

      - name: Create changelog and release
        run: pnpm changelogen --release --push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: |
          pnpm config set npmRegistryServer "https://npm.pkg.github.com"
          pnpm npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}